name: Market Breakout Scan
on:
  schedule:
    - cron: '30 10 * * 1-5' # 4:00 PM IST (after market close)
jobs:
  run-scanner:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Script
        env:
          UPSTOX_ACCESS_TOKEN: ${{ secrets.UPSTOX_ACCESS_TOKEN }}
        run: breakoutdashapp.py
      - name: Save to Repository
        run: |
          git config --local user.name "github-actions"
          git add breakout_results.csv
          git commit -m "Update Breakouts $(date)" || exit 0
          git push
